name: My Github workflow
on:
  push:
    branches:
      -main
env:
  PROJECT_NAME: GitHub-Actions-Demo
  COURSE: LLMOPS-with-GitHub-Actions

jobs:
  myexamplejob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Checkout the repository"
      - name: Checkouut repository
        uses: actions/checkout@v4
      - run: echo "This is my first GitHub workflow"
      - run: echo "This is the env ${{ env.PROJECT_NAME }} and course ${{ env.COURSE }}"
      

    